### ISSUE TITLE
SegFault when using an AQL for loop through edges

### ISSUE THREAD

**Issue by KevinAuSon** [arangodb/arangodb#12507]
## My Environment

* __ArangoDB Version__:        3.7.1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:        Single Server
* __Deployment Strategy__:   ArangoDB Starter in Docker
* __Infrastructure__:               AWS
* __Operating System__:       Linux version 4.15.0-1065-aws (buildd@lgw01-amd64-035) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04))
* __Total RAM in your machine__:        4GB
* __Used Package__:              Debian or Ubuntu .deb

Hello, I run into troubles after having updated the arangodb version to 3.7.1.
Each time that I am using the AQL command below, the container stops with a segfault. It is the same with all the edge types and databases.

```
FOR vertex, edge IN 1 OUTBOUND @_id @edge_name
    return vertex
```

Here are the logs:

```
arangodb.1| 2020-08-24T13:34:09Z [1] FATAL [a7902] {crash} ArangoDB 3.7.1 [linux], thread 6 [SchedWorker] caught unexpected signal 11 (SIGSEGV) accessing address 0x0000000000000040: signal handler invoked
arangodb.1| 2020-08-24T13:34:09Z [1] INFO [308c3] {crash} frame 1 [0x00007f05c02da56d] *no symbol name available for this frame
arangodb.1| 2020-08-24T13:34:09Z [1] INFO [308c3] {crash} frame 2 [0x00007f05c325a515] *no symbol name available for this frame
arangodb.1| 2020-08-24T13:34:09Z [1] INFO [308c3] {crash} frame 3 [0x00007f05c0dbe933] *no symbol name available for this frame
arangodb.1| 2020-08-24T13:34:09Z [1] INFO [308c3] {crash} frame 4 [0x00007f05c0c7b946] *no symbol name available for this frame
arangodb.1| 2020-08-24T13:34:09Z [1] INFO [308c3] {crash} frame 5 [0x00007f05c0dcf0ea] *no symbol name available for this frame
arangodb.1| 2020-08-24T13:34:09Z [1] INFO [308c3] {crash} frame 6 [0x00007f05c0dd0c6a] *no symbol name available for this frame
arangodb.1| 2020-08-24T13:34:09Z [1] INFO [308c3] {crash} frame 7 [0x00007f05c0dd2d02] *no symbol name available for this frame
arangodb.1| 2020-08-24T13:34:09Z [1] INFO [308c3] {crash} frame 8 [0x00007f05c0fdd4da] *no symbol name available for this frame
arangodb.1| 2020-08-24T13:34:09Z [1] INFO [308c3] {crash} frame 9 [0x00007f05c0170d1e] *no symbol name available for this frame
arangodb.1| 2020-08-24T13:34:09Z [1] INFO [308c3] {crash} frame 10 [0x00007f05c0fd6584] *no symbol name available for this frame
arangodb.1| 2020-08-24T13:34:09Z [1] INFO [308c3] {crash} frame 11 [0x00007f05c12c8bcc] *no symbol name available for this frame
arangodb.1| 2020-08-24T13:34:09Z [1] INFO [308c3] {crash} frame 12 [0x00007f05c12c9e69] *no symbol name available for this frame
arangodb.1| 2020-08-24T13:34:09Z [1] INFO [308c3] {crash} frame 13 [0x00007f05c133dfe6] *no symbol name available for this frame
arangodb.1| 2020-08-24T13:34:09Z [1] INFO [308c3] {crash} frame 14 [0x00007f05c13633ca] *no symbol name available for this frame
arangodb.1| 2020-08-24T13:34:09Z [1] INFO [308c3] {crash} frame 15 [0x00007f05c1076155] *no symbol name available for this frame
arangodb.1| 2020-08-24T13:34:09Z [1] INFO [308c3] {crash} frame 16 [0x00007f05c122b579] *no symbol name available for this frame
arangodb.1| 2020-08-24T13:34:09Z [1] INFO [308c3] {crash} frame 17 [0x00007f05c02d6fdb] *no symbol name available for this frame
arangodb.1| 2020-08-24T13:34:09Z [1] INFO [308c3] {crash} frame 18 [0x00007f05c025bfbf] *no symbol name available for this frame
arangodb.1| 2020-08-24T13:34:09Z [1] INFO [308c3] {crash} frame 19 [0x00007f05c3261068] *no symbol name available for this frame
arangodb.1| 2020-08-24T13:34:09Z [1] INFO [ded81] {crash} available physical memory: 8362708992, rss usage: 269983744, vsz usage: 1051136000, threads: 28
arangodb.1| automatically choosing storage engine
arangodb.1| 2020-08-24T13:34:21Z [1] INFO [e52b0] ArangoDB 3.7.1 [linux] 64bit, using jemalloc, build tags/v3.7.1-0-gdd98295dcc, VPack 0.1.33, RocksDB 6.8.0, ICU 64.2, V8 7.9.317, OpenSSL 1.1.1g  21 Apr 2020
arangodb.1| 2020-08-24T13:34:21Z [1] INFO [75ddc] detected operating system: Linux version 4.15.0-1065-aws (buildd@lgw01-amd64-035) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #69-Ubuntu SMP Thu Mar 26 02:17:29 UTC 2020
arangodb.1| 2020-08-24T13:34:21Z [1] INFO [25362] {memory} Available physical memory: 8362708992 bytes, available cores: 2
arangodb.1| 2020-08-24T13:34:21Z [1] INFO [43396] {authentication} Jwt secret not specified, generating...
arangodb.1| 2020-08-24T13:34:21Z [1] INFO [144fe] using storage engine 'rocksdb'
arangodb.1| 2020-08-24T13:34:21Z [1] INFO [3bb7d] {cluster} Starting up with role SINGLE
arangodb.1| 2020-08-24T13:34:21Z [1] INFO [6ea38] using endpoint 'http+tcp://0.0.0.0:8529' for non-encrypted requests
arangodb.1| 2020-08-24T13:34:21Z [1] INFO [a1c60] {syscall} file-descriptors (nofiles) hard limit is 1048576, soft limit is 1048576
arangodb.1| 2020-08-24T13:34:21Z [1] INFO [3844e] {authentication} Authentication is turned on (system only), authentication for unix sockets is turned on
arangodb.1| 2020-08-24T13:34:21Z [1] WARNING [ad4b2] found existing lockfile '/var/lib/arangodb3/LOCK' of previous process with pid 1, and that process seems to be still running
arangodb.1| 2020-08-24T13:34:21Z [1] INFO [e6460] created base application directory '/var/lib/arangodb3-apps/_db'
arangodb.1| 2020-08-24T13:34:22Z [1] INFO [cf3f4] ArangoDB (version 3.7.1 [linux]) is ready for business. Have fun!
```

Thank you very much for your time and experience!
Nicolas

**Comment by jsteemann** [comment]
Thanks for the bug report. Will check...

**Comment by jsteemann** [comment]
Can you try adjusting the query string so it becomes
```
FOR vertex, edge IN 1 OUTBOUND @_id @@edge_name
    return vertex
```
and use a collection name bind parameter named `@edge_name`?
AFAICS this should work. 
Will now try to figure out why the simple bind parameter does not work as expected.

**Comment by KevinAuSon** [comment]
You are right, it does work with a collection name bind. 
What are the differences between the two?

**Comment by jsteemann** [comment]
It's the internal code path that is different for the two.
It worked in 3.6, so it looks like a regression and I will try to fix it.

**Comment by jsteemann** [comment]
Fixed via the above PRs.
The bugfix should be released with either 3.7.2 or 3.7.3. I can't say for sure yet.

**Comment by Simran-B** [comment]
Setting milestone to 3.7.3 just so this ticket won't be forgotten.

**Comment by insider777** [comment]
Thank god somone discovered this i was like wtf does it keep crashing 😄

**Comment by maxkernbach** [comment]
Hi @KevinAuSon and @insider777,

Version 3.7.3, which includes a fix for this issue, has just been released.

From the [Changelog](https://github.com/arangodb/arangodb/blob/19b71a404cc119c65589f8da0c36e3a70e1eddd4/CHANGELOG#L296):

> * Fixed issue #12507: SegFault when using an AQL for loop through edges.

Please comment in case the SegFault still occurs after upgrading.

Thanks
