### ISSUE TITLE
ArangoSearch wrong result with NGRAM_MATCH

### ISSUE THREAD

**Issue by ignaciogallegossanchez** [arangodb/arangodb#12877]
## My Environment

* __ArangoDB Version__:        3.7.2-1
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Single Server
* __Deployment Strategy__:   Manual Start in Docker
* __Configuration__:               no notable settings
* __Infrastructure__:               own
* __Operating System__:        MacOS 10.15.7 (19H2)
* __Total RAM in your machine__:        16Gb
* __Disks in use__:        SSD 
* __Used Package__:   Docker - official Docker library

## Component, Query & Data

__Affected feature__:
AQL query using web interface

__AQL query (if applicable)__:
```
for c in vw_after
    SEARCH
        (
            c.pageAvailabilities.pageInfo.tvShowEID == null AND
            NGRAM_MATCH(c.name_normalized, "the amazing spider", 0.85, 'osp_ngram_title') 
        )
    return c.metadata.name
```
__AQL explain and/or profile (if applicable)__:

__Dataset__:
Currently this documents in the collection (important, in this order):
```
[
  {
    "_key": "MFO_0000033931_PAGE_HD",
    "_id": "video/MFO_0000033931_PAGE_HD",
    "_rev": "_bSUEXJO---",
    "metadata": {
      "name": "La habitación del pánico"
    },
    "pageAvailabilities": [
      {
        "pageInfo": {
          "tvShowEID": null
        }
      }
    ],
    "name_normalized": "la habitacion del panico"
  },
  {
    "_key": "MFO_0000020049_PAGE_4K",
    "_id": "video/MFO_0000020049_PAGE_4K",
    "_rev": "_bSUFfJG---",
    "metadata": {
      "name": "The Amazing Spider-Man 2: El poder de Electro"
    },
    "pageAvailabilities": [
      {
        "pageInfo": {
          "tvShowEID": null
        }
      }
    ],
    "name_normalized": "the amazing spider man 2 el poder de electro"
  },
  {
    "_key": "MFO_0000011673_PAGE_HD",
    "_id": "video/MFO_0000011673_PAGE_HD",
    "_rev": "_bSUGzAa---",
    "metadata": {
      "name": "The Amazing Spider-Man 2"
    },
    "pageAvailabilities": [
      {
        "pageInfo": {
          "tvShowEID": null
        }
      }
    ],
    "name_normalized": "the amazing spider man 2"
  }
]
```

The view "vw_after" links are:

```
  "links": {
    "video": {
      "analyzers": [
        "identity"
      ],
      "fields": {
        "name_normalized": {
          "analyzers": [
            "osp_ngram_title"
          ]
        }
      },
      "includeAllFields": true,
      "storeValues": "id",
      "trackListPositions": false
    }
  },
```

And the analyzer is defined as:
```
{
  "revision": 0,
  "name": "osp_ngram_title",
  "type": "ngram",
  "properties": {
    "min": 2,
    "max": 2,
    "preserveOriginal": false,
    "startMarker": "",
    "endMarker": "",
    "streamType": "utf8"
  },
  "features": [
    "position",
    "norm",
    "frequency"
  ]
}
```

__Size of your Dataset on disk__:

__Replication Factor & Number of Shards (Cluster only)__:
Not applicable

## Steps to reproduce

1. Do the search with the 3 documents shown in the collection --> 0 results
2. Remove the first (not matching) document MFO_0000033931_PAGE_HD -->OK
3. Do the search again --> 2 results

__Problem__:

The search result are inconsistent depending on the collection content

__Expected result__:

2 Results always, without need to remove the first one

**Comment by gnusi** [comment]
@ignaciogallegossanchez thank you for letting us know, we'll take a look and get back to you.

**Comment by Dronplane** [comment]
Hi @ignaciogallegossanchez! We have fixed the issue. Fix will be available in one of the upcoming releases.

**Comment by ignaciogallegossanchez** [comment]
Perfect! Thanks :)

**Comment by Simran-B** [comment]
@Dronplane Which versions will contain the fix?

**Comment by Dronplane** [comment]
Expecting it to be in 3.7.5

**Comment by maxkernbach** [comment]
Hi @ignaciogallegossanchez,

In the meantime version 3.7.6, which includes a fix for this issue, has been released.

In case you still reproduce this bug with a recent version, please comment.
