### ISSUE TITLE
Failed to load API definition

### ISSUE THREAD

**Issue by dsonet** [arangodb/arangodb#4453]
## my environment running ArangoDB
I'm using the latest ArangoDB of the respective release series:
- [x] 3.3.3

Mode:
- [x] Single-Server

Storage-Engine:
- [x] mmfiles

On this operating system:
- [x] Windows, version: 10

### this is a web interface-related issue:
I'm using the web interface with this browser:     running on this OS:
- [x] authentication is enabled?
- [ ] _system database?

These are the steps to reproduce:
1) open the browser on http://127.0.0.1:8529
2) log in as ...
3) use database [ ] `_system` [ ] other: 
4) click 'Services', on any service, navigate to API tab, then you would got 'Failed to load API definition',
'Unauthorized http://127.0.0.1:8529/_db/mydb/_admin/aardvark/foxxes/docs/swagger.json?mount=/apikeys'
I discovered because of the header 'Authorization: bearer null'.

**Comment by maxkernbach** [comment]
Hi,

thanks for reporting the bug, it is reproducible with version 3.3.3.

**Comment by davidmw** [comment]
Same problem here after the upgrade to 3.3.3.

**Comment by ralfr** [comment]
Any update on this?

**Comment by solisoft** [comment]
Any News?

**Comment by dothebart** [comment]
Hi, we're pretty sure that this is caused by 3444c2906d1f5a7fbfdb04c5511688d115d1a031 . It will be reverted with 3.3.4 - which is not ready yet. 

Its probably simple enough to edit it into the minified aardvark file if you need this to be working urgently:
js/apps/system/_admin/aardvark/APP/frontend/build/app.min.js

Cheers, 
Willi

**Comment by hkernbach** [comment]
Edit the file: `js/server/assets/swagger/index.html` in row 102.

If you have sessionStorage defined there, switch to:
```var jwt = localStorage.getItem("jwt");```

If you have localStorage defined there, switch to:
```var jwt = sessionStorage.getItem("jwt");```

**Comment by mtanvir** [comment]
@hkernbach I edited the file to switch from localStorage to sessionStorage as you suggested. It doesn't work. Did the restart as well but no luck.

**Comment by hkernbach** [comment]
Hm ... bad to hear that. We'll fix this asap.

**Comment by krngd2** [comment]
Any updates on it ?

**Comment by milko** [comment]
I also tried to edit the js/server/assets/swagger/index.html file but it doesn't work: is there any information on when the fix will be put? Or if there is a temporary fix, what is it?

Thanks

**Comment by arn-the-long-beard** [comment]
Hello. I also have the same issue. I did not change my Arango for 3 weeks. How can the bug happened even without any change  ?

**Comment by ArnoBuschmann** [comment]
Changing the swagger file in row 102 doesn't work for me either, so the only successful way for me to get the swagger api back was to revert back to version 3.3.2.

But then, somehow, it updated itself also to version 3.3.3 and probably @arn-the-long-beard guessed right that sudo apt-get update is causing the update.

Now I have to revert back to 3.3.2. and hope it stays there for a while so I can work with the api.

**Comment by arn-the-long-beard** [comment]
Hei @ArnoBuschmann  :)

I also followed the instructions given here and on slack. But it did not work neither.

So, I updated Arangodb to the next version , the 3.3.4 :)

The UI is a bit different on the API generated in the new version and I like the new color ( **It is nice :D** )

So the temporary solution can be to **downgrade** , or **upgrade**. 

But when I tried to go back to 3.3.3 ( just to test ) I got some error message

> FATAL ERROR: EXIT_DOWNGRADE_REQUIRED - "db downgrade required" 

Did you get this when you went back to 3.3.2 ?

**Now to come back to the subject:**

 I am using opera system for web browser, I should have try to test with Chrome or Firefox. Could this have an influence on the issue ? Maybe do they handle the session storage differently.  I  will try on an other machine  later this afternoon.

**Comment by ArnoBuschmann** [comment]
Hi @arn-the-long-beard,
oh yes, didn't noticed 3.3.4 is already available, so I just upgraded to that one. And no, I didn't got the downgrade fatal error.

**Comment by maxkernbach** [comment]
Hi @arn-the-long-beard and @ArnoBuschmann,

version 3.3.4 is not released yet. Could you please tell me what system you are using and in which way you upgraded to install version 3.3.4?

Thanks

**Comment by ArnoBuschmann** [comment]
Hi @maxkernbach, I used the tech preview 3.3.4 version, you find more information on that here: https://arangodb.com/download-technical-preview/

**Comment by maxkernbach** [comment]
Hi @ArnoBuschmann,

you are using the tech preview version 3.4 and not version 3.3.4 in this case right?

**Comment by arn-the-long-beard** [comment]
Yes sorry for my fail. **It is the 3.4 version I am using**. I edit my post. There is no 3.3.4

**Comment by maxkernbach** [comment]
@arn-the-long-beard 
No problem, thanks for clarifying that.

**Comment by alexpavlovaskblue** [comment]
Hi,
I read this issue as I had the same error.
Well, I just reverted to the 3.3.2 version but unfortunately I got this problem:

401 : Unauthorized http://gravidashff.com:8529/_db/beaconet/_admin/aardvark/foxxes/docs/swagger.json?mount=%2Fdemo

How can I resolve it?

Thanks in advance!


Best regards

**Comment by OmarAyo** [comment]
Hi @alexpavlovaskblue ,

We have released 3.3.4, and it includes a fix for it
Please let us know if the issue persists.

**Comment by noisypebble** [comment]
I was having the same issue on 3.3.3. I found this thread, updated to 3.3.4 and issue was resolved yesterday. Now today I'm getting the same thing on 3.4.4:

Unauthorized http://localhost:8529/_db/test/_admin/aardvark/foxxes/docs/swagger.json?mount=/foxxtest

**Comment by maxkernbach** [comment]
Hi @noisypebble,

you mentioned that the error occurred on version 3.4.4, you refer to 3.3.4 right? I installed the same service on 3.3.3 and on an upgraded version 3.3.4 (3.3.3 -> 3.3.4) on Ubuntu. The service, which was installed on 3.3.3 showed the same error message as yours (Unauthorized) on 3.3.4, while the API of the same service installed on 3.3.4 worked on 3.3.4.

**Comment by noisypebble** [comment]
Hi @maxkernbach,

Seems to be working now. I thought it might have returned after a reboot of the the ArangoDB server but I think now it was the browser cache as you mentioned.

Thanks!

**Comment by maxkernbach** [comment]
Thanks for your feedback, i am closing this issue for now.
Please feel free to comment and reopen in case this bug persists in version 3.3.4.

**Comment by CBlinguland** [comment]
Hi,

this error re-occures with 3.4 devel (windows) but not in 3.4 milestone0 (win).

**Comment by OmarAyo** [comment]
Hi,

We fixed the upload mechanism in nightly which was the reason for this

**Comment by krngd2** [comment]
chosing OrangoDB was a mistake

**Comment by OmarAyo** [comment]
Hi @krngd2 

Could you please elaborate 

We are here to help you !

Best

**Comment by bugger11** [comment]
I'm still experiencing this issue. All services give the error:
Failed to load API definition.
NetworkError when attempting to fetch resource. http://192.168.1.1:8529/_db/_system/_admin/aardvark/foxxes/docs/swagger.json?mount=/aye-aye

I start ArangoDB like this: # /usr/bin/arangod --server.endpoint "http+tcp://192.168.1.1:8529"

INFO ArangoDB 3.4.0 [linux] 64bit, using jemalloc, build , VPack 0.1.33, RocksDB 5.16.0, ICU 58.1, V8 5.7.492.77, OpenSSL 1.1.1a  20 Nov 2018

INFO detected operating system: Linux version 4.19.12-arch1-1-ARCH (builduser@heftig-21538) (gcc version 8.2.1 20181127 (GCC)) #1 SMP PREEMPT Fri Dec 21 13:56:54 UTC 2018

Mode:   Single-Server
Storage-Engine:   mmfiles

I'm using Firefox to access the Web UI.

These are the steps to reproduce:

    open the browser on http://192.168.11:8529
    log in as root
    use database _system (or any other db)
    click 'Services', on any service, navigate to API tab, then you would the error shown above
