### ISSUE TITLE
Combination of Equi-Join and IN in hash index

### ISSUE THREAD

**Issue by carli2** [arangodb/arangodb#6744]
__AQL query__:

```AQL
FOR v in variations
FILTER v.source == 1 // TODO: @source



LET sales = (
    FOR o in orders
    FILTER v.source == o.source && v.id IN o.orderItems[*].itemVariationId
    FOR sale in o.orderItems
    FILTER sale.itemVariationId == v.id
    COLLECT AGGREGATE soldItems = SUM(sale.quantity), revenue = SUM(sale.quantity * sale.priceNet)
    RETURN {soldItems: soldItems, revenue: revenue}
)

RETURN {
    vid: v.id,
    purchasePrice: v.purchasePrice,
    soldIttems: sales.soldItems,
    soldRevenue: sales.soldRevenue
}


```

__AQL explain (if applicable)__:
```
Execution plan:
 Id   NodeType               Est.   Comment
  1   SingletonNode             1   * ROOT
 21   IndexNode             17741     - FOR v IN variations   /* hash index scan */
 18   SubqueryNode          17741       - LET sales = ...   /* subquery */
  5   SingletonNode             1         * ROOT
 22   IndexNode             37207           - FOR o IN orders   /* skiplist index scan */
 23   CalculationNode       37207             - LET #12 = (v.`id` in o.`orderItems`[*].`itemVariationId`)   /* simple expression */   /* collections used: v : variations, o : orders */
  8   FilterNode            37207             - FILTER #12
  9   CalculationNode       37207             - LET #14 = o.`orderItems`   /* attribute expression */   /* collections used: o : orders */
 10   EnumerateListNode   3720700             - FOR sale IN #14   /* list iteration */
 11   CalculationNode     3720700               - LET #16 = (sale.`itemVariationId` == v.`id`)   /* simple expression */   /* collections used: v : variations */
 12   FilterNode          3720700               - FILTER #16
 13   CalculationNode     3720700               - LET #18 = sale.`quantity`   /* attribute expression */
 14   CalculationNode     3720700               - LET #20 = (sale.`quantity` * sale.`priceNet`)   /* simple expression */
 15   CollectNode         2976560               - COLLECT AGGREGATE soldItems = SUM(#18), revenue = SUM(#20)   /* sorted */
 16   CalculationNode     2976560               - LET #22 = { "soldItems" : soldItems, "revenue" : revenue }   /* simple expression */
 17   ReturnNode          2976560               - RETURN #22
 19   CalculationNode       17741       - LET #24 = { "vid" : v.`id`, "purchasePrice" : v.`purchasePrice`, "soldIttems" : sales.`soldItems`, "soldRevenue" : sales.`soldRevenue` }   /* simple expression */   /* collections used: v : variations */
 20   ReturnNode            17741       - RETURN #24

Indexes used:
 By   Type       Collection   Unique   Sparse   Selectivity   Fields                      Ranges
 21   hash       variations   false    false         0.01 %   [ `source` ]                (v.`source` == 1)
 22   skiplist   orders       false    false            n/a   [ `source`, `createdAt` ]   (1 == o.`source`)

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   move-calculations-up-2
  4   move-filters-up-2
  5   propagate-constant-attributes
  6   use-indexes
  7   remove-filter-covered-by-index
  8   remove-unnecessary-calculations-2

```

__Dataset__:
you can boil examples down to:
 - two collections a and b
 - a.source, a.id is unique
 - b.source references a.source
 - b.ids[*].id references a.id
 - *`b.source, b.ids[*].id` is a hash index*
 - for a: {source: 1, id: 1}
 - for b: {source: 1, ids: [[id: 1, amount: 3}]}
 - query to test: `FOR xa in a FOR xb in b FILTER xa.source == xb.source && xa.id IN xb.ids[*].id RETURN [xa,xb]`

__Problem__:
Filtering equality AND `IN` in one filter does not work. The first condition is somehow done by index, but the second condition is evaluated over millions of datasets while it could be read from the index.

Removing the first part of the filter condition (equality of .source) makes the query fast. Combining == and IN in one FILTER. I tried to find a workaround (separate filter and so on), but none worked.

__Expected result__:

#22 should rather use [source, orderItems[*].itemVariationId] as index

**Comment by carli2** [comment]
ArangoDB version: 3.3
Deployment mode: singleserver
Storage engine: default one from rpm installation
OS: linux

**Comment by carli2** [comment]
Version is: *3.3.16*

does the optimizer behave different depending on OS?

As far as I can see, the issue is that ArangoDB does not fully discover all versions of index use. If I move `a.source == b.source` into the SUM calculation (`SUM(a.source == b.source ? some_value : 0)`), the optimizer does find the better use of index `value IN array` - also with better cost estimation. So if the optimizer would try if it will find better cost estimation by leaving out checking `source` and doing IN by index (while doing `source` by LET+FILTER), a much better plan would be generated.

**Comment by jsteemann** [comment]
> does the optimizer behave different depending on OS?

No, it doesn't. But there may be differences, known issues, and bugs already fixed in some of the ArangoDB minor or bugfix versions, so we routinely ask about the exact type of deployment. Optimizer details and index usage mostly depend on ArangoDB version, storage engine (which in your case is probably MMFiles as it is the default engine in 3.3), the amount of documents in the underlying collections plus the average selectivity of the indexes.

Regarding the filter conditions: the optimizer can normally handle `==` and `IN` in the same filter condition, at least for non-array indexes. This case may be special because of the usage of an array index, but that is just a guess for now.

Apart from that, I am not 100% clear how your indexes are setup. When you are saying
> a.source, a.id is unique
does it mean that the *combination* of `source` and `id` is unique, or are the separate indexes on each attribute. I am assuming the former (a combined unique index).

So here is my setup that I used trying to replicate the issue according to your setup description:
```js
db._drop("a");
db._drop("b");
db._create("a");
db._create("b");
db.a.insert({ source:1, id:1 });
db.b.insert({ source:1, ids: [{ id:1, amount: 3 }] });
db.a.ensureIndex({ type: "hash", fields: ["source", "id"], unique: true });
db.b.ensureIndex({ type: "hash", fields: ["source", "ids[*].id"] });
db._explain(`FOR xa in a FOR xb in b FILTER xa.source == xb.source && xa.id IN xb.ids[*].id RETURN [xa,xb]`);
```
Using that setup, I see no index being used for the query in 3.3.17.
For 3.4.0RC2 however I see the combined array index on `source` and `ids[*].id` being used, and as a bonus the filter is also removed there:
```
Query String:
 FOR xa in a FOR xb in b FILTER xa.source == xb.source && xa.id IN xb.ids[*].id RETURN [xa,xb]

Execution plan:
 Id   NodeType                  Est.   Comment
  1   SingletonNode                1   * ROOT
  2   EnumerateCollectionNode      1     - FOR xa IN a   /* full collection scan */
  8   IndexNode                    1       - FOR xb IN b   /* hash index scan */
  6   CalculationNode              1         - LET #6 = [ xa, xb ]   /* simple expression */   /* collections used: xa : a, xb : b */
  7   ReturnNode                   1         - RETURN #6

Indexes used:
 By   Type   Collection   Unique   Sparse   Selectivity   Fields                      Ranges
  8   hash   b            false    false       100.00 %   [ `source`, `ids[*].id` ]   ((xa.`source` == xb.`source`) && (xa.`id` in xb.`ids`[*].`id`))
```
So chances are that the optimizer makes a better index choice for this query in 3.4 than in 3.3. I am however not sure if my setup matches yours and if the index choice will vary depending on number of documents in the collections plus underlying index selectivity. Is it possible for you to give 3.4.0RC2 a try with your dataset and check if it improves the situation? Thanks.

**Comment by carli2** [comment]
The combination of source+id is unique in this example since the software is multi-client.

Table a contains ~13,000 documents while b contains ~10,000.

Are there any .rpm packages for 3.4 so I can test if the new version has implemented this new index scan variant?

**Comment by jsteemann** [comment]
The 3.4.0RC2 packages can be found here:
https://www.arangodb.com/download-technical-preview/
There are also .rpm packages available.

**Comment by carli2** [comment]
Hello Jan,

I tried 3.4.0RC2 and got still the same issue (here with full query):
```
Query String:
 FOR v in variations
 FILTER v.source == @source
 FOR a in articles
 FILTER a.source == v.source && a.id == v.itemId
 LET stock = (
     FOR s in v.stock
     COLLECT AGGREGATE physicalStock = SUM(s.physicalStock), netStock = SUM(s.netStock)
     RETURN {physicalStock: physicalStock, netStock: netStock}
 )[0]
 LET sales = (
     FOR o in orders
     //FILTER o.source == v.source TODO: optimizer-Bug macht es zu langsam
     FILTER o.source == v.source && v.id IN o.orderItems[*].itemVariationId
     FOR sale in o.orderItems
     FILTER sale.itemVariationId == v.id
     COLLECT AGGREGATE soldItems = SUM(sale.quantity), revenue = SUM(sale.quantity * 
 sale.amounts[0].priceNet)
     RETURN {soldItems: soldItems, revenue: revenue}
 )[0]
 LET variationSalesPrices = ZIP((FOR p in v.variationSalesPrices RETURN p.salesPriceId), (FOR p in 
 v.variationSalesPrices RETURN p.price))
 // TODO: stattdessen in eine resulttbl inserten, die wiederum indiziert ist
 RETURN {
     name: a.texts[0].name1,
     img: a.itemImages[0].u...

Execution plan:
 Id   NodeType               Est.   Comment
  1   SingletonNode             1   * ROOT
 51   IndexNode             17741     - FOR v IN variations   /* hash index scan */
 50   IndexNode             17741       - FOR a IN articles   /* hash index scan */
 16   SubqueryNode          17741         - LET #5 = ...   /* subquery */
  8   SingletonNode             1           * ROOT
  9   CalculationNode           1             - LET #28 = v.`stock`   /* attribute expression */   /* collections used: v : variations */
 10   EnumerateListNode       100             - FOR s IN #28   /* list iteration */
 11   CalculationNode         100               - LET #30 = s.`physicalStock`   /* attribute expression */
 12   CalculationNode         100               - LET #32 = s.`netStock`   /* attribute expression */
 13   CollectNode               1               - COLLECT AGGREGATE physicalStock = SUM(#30), netStock = SUM(#32)   /* sorted */
 48   LimitNode                 1               - LIMIT 0, 1
 14   CalculationNode           1               - LET #34 = { "physicalStock" : physicalStock, "netStock" : netStock }   /* simple expression */
 15   ReturnNode                1               - RETURN #34
 31   SubqueryNode          17741         - LET #14 = ...   /* subquery */
 18   SingletonNode             1           * ROOT
 52   IndexNode             37207             - FOR o IN orders   /* skiplist index scan */
 53   CalculationNode       37207               - LET #36 = (v.`id` in o.`orderItems`[*].`itemVariationId`)   /* simple expression */   /* collections used: v : variations, o : orders */
 21   FilterNode            37207               - FILTER #36
 22   CalculationNode       37207               - LET #38 = o.`orderItems`   /* attribute expression */   /* collections used: o : orders */
 23   EnumerateListNode   3720700               - FOR sale IN #38   /* list iteration */
 24   CalculationNode     3720700                 - LET #40 = (sale.`itemVariationId` == v.`id`)   /* simple expression */   /* collections used: v : variations */
 25   FilterNode          3720700                 - FILTER #40
 26   CalculationNode     3720700                 - LET #42 = sale.`quantity`   /* attribute expression */
 27   CalculationNode     3720700                 - LET #44 = (sale.`quantity` * sale.`amounts`[0].`priceNet`)   /* simple expression */
 28   CollectNode               1                 - COLLECT AGGREGATE soldItems = SUM(#42), revenue = SUM(#44)   /* sorted */
 49   LimitNode                 1                 - LIMIT 0, 1
 29   CalculationNode           1                 - LET #46 = { "soldItems" : soldItems, "revenue" : revenue }   /* simple expression */
 30   ReturnNode                1                 - RETURN #46
 38   SubqueryNode          17741         - LET #18 = ...   /* subquery */
 33   SingletonNode             1           * ROOT
 34   CalculationNode           1             - LET #48 = v.`variationSalesPrices`   /* attribute expression */   /* collections used: v : variations */
 35   EnumerateListNode       100             - FOR p IN #48   /* list iteration */
 36   CalculationNode         100               - LET #50 = p.`salesPriceId`   /* attribute expression */
 37   ReturnNode              100               - RETURN #50
 44   SubqueryNode          17741         - LET #21 = ...   /* subquery */
 39   SingletonNode             1           * ROOT
 40   CalculationNode           1             - LET #52 = v.`variationSalesPrices`   /* attribute expression */   /* collections used: v : variations */
 41   EnumerateListNode       100             - FOR p IN #52   /* list iteration */
 42   CalculationNode         100               - LET #54 = p.`price`   /* attribute expression */
 43   ReturnNode              100               - RETURN #54
 32   CalculationNode       17741         - LET sales = #14[0]   /* simple expression */
 17   CalculationNode       17741         - LET stock = #5[0]   /* simple expression */
 46   CalculationNode       17741         - LET #56 = { "name" : a.`texts`[0].`name1`, "img" : a.`itemImages`[0].`url`, "id" : a.`id`, "vid" : v.`id`, "purchasePrice" : v.`purchasePrice`, "manufacturer" : a.`manufacturerId`, "physicalStock" : stock.`physicalStock`, "netStock" : stock.`netStock`, "soldItems" : sales.`soldItems`, "soldRevenue" : sales.`revenue`, "sortCol" : sales.`revenue`, "variationSalesPrices" : ZIP(#18, #21), "worth" : (stock.`netStock` * v.`purchasePrice`), "source" : "" }   /* simple expression */   /* collections used: a : articles, v : variations */
 47   ReturnNode            17741         - RETURN #56

Indexes used:
 By   Type       Collection   Unique   Sparse   Selectivity   Fields                      Ranges
 51   hash       variations   false    false         0.01 %   [ `source` ]                (v.`source` == "")
 50   hash       articles     true     false       100.00 %   [ `source`, `id` ]          ((a.`source` == "") && (a.`id` == v.`itemId`))
 52   skiplist   orders       false    false            n/a   [ `source`, `createdAt` ]   (o.`source` == "")

Functions used:
 Name   Deterministic   Cacheable   Uses V8
 ZIP    true            true        false  

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   remove-unnecessary-calculations
  4   optimize-subqueries
  5   move-calculations-up-2
  6   move-filters-up-2
  7   propagate-constant-attributes
  8   use-indexes
  9   remove-filter-covered-by-index
 10   remove-unnecessary-calculations-2
 11   move-calculations-down
```

Instead of using "IN" index, a index is chosen that only filters for `source` (` 52   skiplist   orders       false    false            n/a   [ `source`, `createdAt` ]   (o.`source` == "")`) while the more expensive "IN" filter is done in the loop.

**Comment by jsteemann** [comment]
Hi @carli2, thanks for getting back!
I understand that you are expecting usage of a different index than is actually used. The problem is that I still don't know the actual index setup and the query to look at, because at least the query you are using now seems to be different to the original question (which already contained two different queries).
Can we please try this with a minimal example showing the problem, ideally together with the *exact* index setup for the involved collections? The easiest way to get there is to run the minimal query showing the problem in the ArangoDB web interface, create a "debug package" there and provide it here.
Thanks again!

**Comment by carli2** [comment]
For the issue, I simplified the query. What you see now is the fully fledged query. Here's the index setup:
 - skiplist source+createdAt
 - hash source+id
 - hash source+orderItems[*].id (I also tried skiplist but same result)

Give me a day so I can send you the full index setup.

**Comment by jsteemann** [comment]
Ok, thanks. As I mentioned, the ArangoDB web interface has some "create debug package" button that can be used to export the query and the index setup easily.
If that is no option for whatever reason, there is also the possibility to use the ArangoShell and run
```
db._collection("collection-name-goes-here").getIndexes();
```
for each of the underlying collections.
Apart from that, if it's all about the index usage and joins, can we stick with the part of the query that causes the performance problems? That would make setup and reproducibility even easier.
Thanks!

**Comment by carli2** [comment]
I did not find the debug button. Maybe you tell me for the next time.

Here's the manual index export:
```
127.0.0.1:8529@dirk> db._collection('articles').getIndexes()
[ 
  { 
    "fields" : [ 
      "_key" 
    ], 
    "id" : "articles/0", 
    "selectivityEstimate" : 1, 
    "sparse" : false, 
    "type" : "primary", 
    "unique" : true 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "source", 
      "id" 
    ], 
    "id" : "articles/144453", 
    "selectivityEstimate" : 1, 
    "sparse" : false, 
    "type" : "hash", 
    "unique" : true 
  } 
]
127.0.0.1:8529@dirk> db._collection('orders').getIndexes()
[ 
  { 
    "fields" : [ 
      "_key" 
    ], 
    "id" : "orders/0", 
    "selectivityEstimate" : 1, 
    "sparse" : false, 
    "type" : "primary", 
    "unique" : true 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "source", 
      "id" 
    ], 
    "id" : "orders/228340", 
    "selectivityEstimate" : 1, 
    "sparse" : false, 
    "type" : "hash", 
    "unique" : true 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "source", 
      "orderItems[*].itemId" 
    ], 
    "id" : "orders/228342", 
    "selectivityEstimate" : 0.000001343818702731177, 
    "sparse" : false, 
    "type" : "hash", 
    "unique" : false 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "source", 
      "orderItems[*].itemVariationId" 
    ], 
    "id" : "orders/228345", 
    "selectivityEstimate" : 0.010125037275394079, 
    "sparse" : false, 
    "type" : "hash", 
    "unique" : false 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "source", 
      "createdAt" 
    ], 
    "id" : "orders/1827683", 
    "sparse" : false, 
    "type" : "skiplist", 
    "unique" : false 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "source", 
      "updatedAt" 
    ], 
    "id" : "orders/1827992", 
    "sparse" : false, 
    "type" : "skiplist", 
    "unique" : false 
  }, 
  { 
    "deduplicate" : false, 
    "fields" : [ 
      "orderItems[*].itemVariationId" 
    ], 
    "id" : "orders/1871701", 
    "selectivityEstimate" : 0.010125037275394079, 
    "sparse" : false, 
    "type" : "hash", 
    "unique" : false 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "source", 
      "orderItems[*].itemVariationId" 
    ], 
    "id" : "orders/1873597", 
    "sparse" : false, 
    "type" : "skiplist", 
    "unique" : false 
  } 
]
127.0.0.1:8529@dirk> db._collection('variations').getIndexes()
[ 
  { 
    "fields" : [ 
      "_key" 
    ], 
    "id" : "variations/0", 
    "selectivityEstimate" : 1, 
    "sparse" : false, 
    "type" : "primary", 
    "unique" : true 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "source", 
      "id" 
    ], 
    "id" : "variations/173207", 
    "selectivityEstimate" : 1, 
    "sparse" : false, 
    "type" : "hash", 
    "unique" : true 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "source", 
      "item.id" 
    ], 
    "id" : "variations/173210", 
    "selectivityEstimate" : 0.7724480018037315, 
    "sparse" : false, 
    "type" : "hash", 
    "unique" : false 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "source", 
      "itemId" 
    ], 
    "id" : "variations/209973", 
    "selectivityEstimate" : 0.7724480018037315, 
    "sparse" : false, 
    "type" : "hash", 
    "unique" : false 
  }, 
  { 
    "deduplicate" : true, 
    "fields" : [ 
      "source" 
    ], 
    "id" : "variations/1870873", 
    "selectivityEstimate" : 0.000056366608421171295, 
    "sparse" : false, 
    "type" : "hash", 
    "unique" : false 
  } 
]
```

The part of the query that makes performance problem is the nested `for` combining && and IN.

This is the minimal version of the query:
```
Query String:
 FOR v in variations
 FILTER v.source == @source
 LET sales = (
     FOR o in orders
     FILTER o.source == v.source // TODO: optimizer Bug
     FILTER v.id IN o.orderItems[*].itemVariationId
     FOR sale in o.orderItems
     FILTER sale.itemVariationId == v.id
     COLLECT AGGREGATE soldItems = SUM(sale.quantity), revenue = SUM(sale.quantity * 
 sale.amounts[0].priceNet)
     RETURN {soldItems: soldItems, revenue: revenue}
 )[0]
 // in eine resulttbl inserten, die wiederum indiziert ist
 RETURN {
     vid: v.id,
     purchasePrice: v.purchasePrice,
     soldItems: sales.soldItems,
     soldRevenue: sales.revenue,
     sortCol: sales.revenue,
     source: @source
 }

Execution plan:
 Id   NodeType               Est.   Comment
  1   SingletonNode             1   * ROOT
 25   IndexNode             17741     - FOR v IN variations   /* hash index scan */
 20   SubqueryNode          17741       - LET #7 = ...   /* subquery */
  5   SingletonNode             1         * ROOT
 26   IndexNode             37207           - FOR o IN orders   /* skiplist index scan */
  9   CalculationNode       37207             - LET #14 = (v.`id` in o.`orderItems`[*].`itemVariationId`)   /* simple expression */   /* collections used: v : variations, o : orders */
 10   FilterNode            37207             - FILTER #14
 11   CalculationNode       37207             - LET #16 = o.`orderItems`   /* attribute expression */   /* collections used: o : orders */
 12   EnumerateListNode   3720700             - FOR sale IN #16   /* list iteration */
 13   CalculationNode     3720700               - LET #18 = (sale.`itemVariationId` == v.`id`)   /* simple expression */   /* collections used: v : variations */
 14   FilterNode          3720700               - FILTER #18
 15   CalculationNode     3720700               - LET #20 = sale.`quantity`   /* attribute expression */
 16   CalculationNode     3720700               - LET #22 = (sale.`quantity` * sale.`amounts`[0].`priceNet`)   /* simple expression */
 17   CollectNode               1               - COLLECT AGGREGATE soldItems = SUM(#20), revenue = SUM(#22)   /* sorted */
 24   LimitNode                 1               - LIMIT 0, 1
 18   CalculationNode           1               - LET #24 = { "soldItems" : soldItems, "revenue" : revenue }   /* simple expression */
 19   ReturnNode                1               - RETURN #24
 21   CalculationNode       17741       - LET sales = #7[0]   /* simple expression */
 22   CalculationNode       17741       - LET #26 = { "vid" : v.`id`, "purchasePrice" : v.`purchasePrice`, "soldItems" : sales.`soldItems`, "soldRevenue" : sales.`revenue`, "sortCol" : sales.`revenue`, "source" : "" }   /* simple expression */   /* collections used: v : variations */
 23   ReturnNode            17741       - RETURN #26

Indexes used:
 By   Type       Collection   Unique   Sparse   Selectivity   Fields                      Ranges
 25   hash       variations   false    false         0.01 %   [ `source` ]                (v.`source` == "")
 26   skiplist   orders       false    false            n/a   [ `source`, `createdAt` ]   (o.`source` == "")

Optimization rules applied:
 Id   RuleName
  1   move-calculations-up
  2   move-filters-up
  3   optimize-subqueries
  4   move-calculations-up-2
  5   move-filters-up-2
  6   propagate-constant-attributes
  7   use-indexes
  8   remove-filter-covered-by-index
  9   remove-unnecessary-calculations-2
 10   move-calculations-down
```

**Comment by vinaypyati** [comment]
Hi @carli2,

Thanks for sending us the index report. If you wish to create a debug package you can open the Web UI and navigate to `QUERIES`. 

Please refer the image below. At the bottom right you would find a yellow color button `Create Debug Package`. This will prompt a dialog with further information. 
![image](https://user-images.githubusercontent.com/34657484/47169251-49b8a380-d303-11e8-83ba-901559422882.png)

This is a easy way to create a zip file with the collections and indexes setup plus some example documents from the collections. Using that debug package we will be more able to analyze this issue because it allows us to run the query in a more similar setup.

Thanks!

**Comment by jsteemann** [comment]
Thanks @vinaypyati !
On a side note: I have tried that setup and chances are that the index selection will be improved with 3.4.0-RC3, which has not been released yet. We expect RC3 to be released within the next few weeks, and it would be very helpful if you could retry the query with it.
Thanks!

**Comment by carli2** [comment]
Here's the dump: 
[debugDump.zip](https://github.com/arangodb/arangodb/files/2493139/debugDump.zip)

**Comment by carli2** [comment]
[debugDump.zip](https://github.com/arangodb/arangodb/files/2493184/debugDump.zip)
this is debugDump with the de-workarounded query

**Comment by vinaypyati** [comment]
Hi @carli2, 

3.4.0-RC3 has been released and it includes a fix for this problem. You can download it from the [download section](https://www.arangodb.com/download-technical-preview/). 

I am closing this ticket now. Please feel free to comment if the issue persists

Thanks!
