### ISSUE TITLE
Have a way to reset/alter the internal sequence generator

### ISSUE THREAD

**Issue by soualid** [arangodb/arangodb#8748]
## My Environment

* __ArangoDB Version__:        3.3.22
* __Storage Engine__:             RocksDB
* __Deployment Mode__:       Master/Slave
* __Deployment Strategy__:   DCOS
* __Infrastructure__:               own
* __Operating System__:        Docker
* __Total RAM in your machine__:        500GB
* __Disks in use__:        SSD
* __Used Package__:              Docker official

## Issue

We experienced a very strange issue yesterday, the database restarted because of an OOM with the following logs:

```
<--- Last few GCs --->

[18:0x7ee7b6039e00]       27 ms: Scavenge 3.3 (7.0) -> 3.2 (7.5) MB, 1.1 / 0.0 ms  allocation failure 
[18:0x7ee7b6039e00]       35 ms: Scavenge 4.2 (7.5) -> 3.9 (10.0) MB, 0.6 / 0.0 ms  allocation failure 


<--- JS stacktrace --->
Cannot get stack trace in GC.
2019-04-11T16:15:21Z [18] FATAL out of memory in V8 (MarkingDeque::EnsureCommitted)
```

After this restart, the unique identifiers automatically generated jumped from `12834483556` to `17301813621345010032` with no reason. 

Do you know how this could have occured? Is it possible to reset this sequence somehow?

Many thanks in advance.

**Comment by soualid** [comment]
Further investigations: 

We tried to change the `keyOptions.lastValue` before restoring a full dump (our `keyOptions.type` is `traditional): it does not seem to work as the last value seems to be automatically shifted to the last `_key` inserted into the database.

The weird thing is that, on an empty database, this sequence seems to be scoped to a single collection, but on the database where this happened, it is definitely database wide, because a new collection also used "shifted" keys. Is it because this database was migrated from previous version (2.x) of ArangoDB?

**Comment by soualid** [comment]
Is it possible to have a confirmation on how the `_key` sequences are generated when using the `traditional` key types, are they database wide or collection wide? Is this related to the version of ArangoDB used?

Many thanks in advance!

**Comment by graetzer** [comment]
Just to confirm you are on the 3.3 series not 3.4 ?

**Comment by soualid** [comment]
Yes, this happened on a database running ArangoDB 3.3.22 (single server).

**Comment by graetzer** [comment]
do you by any chance have custom generated keys that are this big ?

**Comment by soualid** [comment]
That was my guess too after having tested the key generation in the presence of numeric user generated keys (which shift the internal sequence), but we double checked the client code and the only keys we generate are normally alphanumeric and not numeric. But, who knows, maybe someone somewhere inserted such key in the database and removed it afterward, and the fact that this happened just after an out of memory is just a coincidence. 

Anyway, this ticket was more a feature request: for what I know by reading the documentation and the relevant parts of the code, there is no way to reset/alter this sequence, or to use another one. It would be really useful to workaround such issues to have a way to to so when the primary sequence get "corrupted" somehow. 

Actually, the only workaround would be to delegate the key generation to another process, but that would be complicated, less reliable and more error prone than a built-in sequence generator. 

Thanks!

**Comment by graetzer** [comment]
ok so after some research we have definetly found a bug in the recovery procedure. If you have an application generated numeric document `_key` this can cause the global tick value to be set to a large value (which in turn leads to a jump in the autogenerated keys).

We are going to fix it in 3.4
https://github.com/arangodb/arangodb/pull/8856

**Comment by soualid** [comment]
Thanks for the follow-up, is there a way to sanitize the affected sequence by resetting it to a specific value? Apart from this bug, which is now fixed, it could be useful to provide users a solution to fix a sequence broken by error by a query which inserted a large numeric value as a document key. 

Should we create another ticket for that? 

Thanks.

**Comment by graetzer** [comment]
I'm afraid this will be difficult, we must guarantee that the generated values always increase

**Comment by soualid** [comment]
Ok, thanks!

**Comment by maxkernbach** [comment]
Hi @soualid,

version 3.4.6, which includes a tick overflow fix (that leads to a jump in the autogenerated keys), has been released.

In case you are still facing this problem with 3.4.6+, please leave a comment and we will reopen this issue.
The latest release is available in the [download section](https://www.arangodb.com/download-major/).
